import * as pdfjsLib from 'pdfjs-dist';

// Helper to resolve public assets correctly on GitHub Pages, subpaths, and root paths
export function resolvePublicUrl(filePath: string): string {
  if (!filePath) return '';
  if (
    filePath.startsWith('http://') ||
    filePath.startsWith('https://') ||
    filePath.startsWith('blob:') ||
    filePath.startsWith('data:')
  ) {
    return filePath;
  }

  // Ensure path starts with a clean '/'
  const normalizedPath = filePath.startsWith('/') ? filePath : `/${filePath}`;
  const base = ((import.meta as any).env?.BASE_URL as string) || '/';

  // If base is root or relative, return absolute normalized path to avoid SPA sub-route path pollution (e.g. /reader/books/...)
  if (!base || base === '/' || base === './' || base === '.') {
    return normalizedPath;
  }

  const cleanBase = base.endsWith('/') ? base.slice(0, -1) : base;
  return `${cleanBase}${normalizedPath}`;
}

// Configure the worker source for pdfjs-dist
let workerInitialized = false;

export function initPdfWorker(): void {
  if (workerInitialized) return;

  try {
    const version = pdfjsLib.version || '6.2.108';
    pdfjsLib.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${version}/build/pdf.worker.min.mjs`;
    workerInitialized = true;
  } catch (err) {
    console.warn('Could not initialize PDF.js worker:', err);
  }
}

// In-memory cache for rendered thumbnails to prevent duplicate rendering
const thumbnailCache = new Map<string, string>();

// In-memory cache for rendered full pages (data URLs) to ensure instant, zero-flicker transitions
const pageImageCache = new Map<string, { dataUrl: string; width: number; height: number }>();

export function getCachedPageImage(cacheKey: string) {
  return pageImageCache.get(cacheKey) || null;
}

export function setCachedPageImage(cacheKey: string, dataUrl: string, width: number, height: number) {
  // Keep cache size bounded (up to 20 pages in memory)
  if (pageImageCache.size > 20) {
    const firstKey = pageImageCache.keys().next().value;
    if (firstKey) pageImageCache.delete(firstKey);
  }
  pageImageCache.set(cacheKey, { dataUrl, width, height });
}

/**
 * Robustly fetch and validate PDF binary bytes.
 * Throws clean, descriptive error messages if the file was not found,
 * returned HTML (e.g. 404 falling back to index.html), or is corrupted.
 */
export async function fetchAndValidatePdfData(pdfUrl: string): Promise<Uint8Array> {
  const resolvedUrl = resolvePublicUrl(pdfUrl);
  const response = await fetch(resolvedUrl);

  if (!response.ok) {
    throw new Error(
      `Could not load PDF file from "${resolvedUrl}" (HTTP ${response.status} ${response.statusText}). Please verify the PDF exists in /public/books.`
    );
  }

  const contentType = response.headers.get('content-type') || '';
  if (contentType.includes('text/html')) {
    throw new Error(
      `The file at "${resolvedUrl}" returned an HTML webpage instead of a PDF document (likely a 404 Not Found fallback). Please ensure the demo books are generated by running "npm run generate-demo".`
    );
  }

  const buffer = await response.arrayBuffer();
  const bytes = new Uint8Array(buffer);

  // Validate PDF header magic bytes "%PDF" (0x25 0x50 0x44 0x46)
  if (bytes.length < 5 || bytes[0] !== 0x25 || bytes[1] !== 0x50 || bytes[2] !== 0x44 || bytes[3] !== 0x46) {
    // If it's plain text or HTML without proper header
    const preview = new TextDecoder('utf-8').decode(bytes.slice(0, 100));
    if (preview.includes('<!DOCTYPE') || preview.includes('<html')) {
      throw new Error(
        `Received HTML instead of a valid PDF document. Please run "npm run generate-demo" to create the demo books.`
      );
    }
    throw new Error(
      `The file at "${resolvedUrl}" is not a valid PDF document (missing %PDF header signature).`
    );
  }

  return bytes;
}

/**
 * Generate a thumbnail from the first page of a PDF document.
 * Returns a data URL (image/png or image/jpeg).
 */
export async function generatePdfThumbnail(pdfUrl: string, targetWidth = 320): Promise<string> {
  initPdfWorker();

  const resolvedUrl = resolvePublicUrl(pdfUrl);

  if (thumbnailCache.has(resolvedUrl)) {
    return thumbnailCache.get(resolvedUrl)!;
  }

  // Check sessionStorage for persisted thumbnail
  const cacheKey = `booknest_thumb_${resolvedUrl}`;
  try {
    const cached = sessionStorage.getItem(cacheKey);
    if (cached) {
      thumbnailCache.set(resolvedUrl, cached);
      return cached;
    }
  } catch {
    // Storage might be restricted
  }

  const version = pdfjsLib.version || '6.2.108';
  const pdfBytes = await fetchAndValidatePdfData(resolvedUrl);

  const loadingTask = pdfjsLib.getDocument({
    data: pdfBytes,
    cMapUrl: `https://cdn.jsdelivr.net/npm/pdfjs-dist@${version}/cmaps/`,
    cMapPacked: true,
  });

  let pdf: pdfjsLib.PDFDocumentProxy | null = null;
  try {
    pdf = await loadingTask.promise;
    const page = await pdf.getPage(1);

    const unscaledViewport = page.getViewport({ scale: 1.0 });
    const scale = targetWidth / unscaledViewport.width;
    const viewport = page.getViewport({ scale });

    const canvas = document.createElement('canvas');
    const context = canvas.getContext('2d', { alpha: false });

    if (!context) {
      throw new Error('Canvas 2D context is not available');
    }

    // Account for device pixel ratio for crisp cover preview
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    canvas.width = Math.floor(viewport.width * dpr);
    canvas.height = Math.floor(viewport.height * dpr);
    canvas.style.width = `${Math.floor(viewport.width)}px`;
    canvas.style.height = `${Math.floor(viewport.height)}px`;

    context.scale(dpr, dpr);

    // Fill with clean background before rendering
    context.fillStyle = '#FFFFFF';
    context.fillRect(0, 0, viewport.width, viewport.height);

    const renderContext = {
      canvasContext: context,
      viewport: viewport,
      canvas: canvas,
    };

    await page.render(renderContext).promise;

    const dataUrl = canvas.toDataURL('image/jpeg', 0.88);
    thumbnailCache.set(resolvedUrl, dataUrl);

    try {
      sessionStorage.setItem(cacheKey, dataUrl);
    } catch {
      // SessionStorage quota exceeded or disabled
    }

    return dataUrl;
  } finally {
    if (pdf) {
      try {
        pdf.cleanup();
      } catch {
        // Ignore cleanup errors
      }
    }
  }
}

export { pdfjsLib };
